name: CI/CD Pipeline with Job Outputs

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:  # Trigger manually via GitHub UI

jobs:
  # Job 1: Build (Triggered on push)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the project
        id: build_step  # This step will generate the output
        run: |
          # Simulate build process and create a version string
          VERSION="v1.0.0"
          echo "Build completed successfully."
          # Set output to pass to the next job
          echo "::set-output name=version::$VERSION"  # This sets the 'version' output

    outputs:
      version: ${{ steps.build_step.outputs.version }}  # Expose the output for other jobs

  # Job 2: Deploy (Triggered manually)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy project
        run: |
          # Access the version output from the build job
          echo "Deploying version ${{ needs.build.outputs.version }} to production..."
