name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggered when there is a push to the 'main' branch
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  # Job 1: Build (Triggered on push)
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only runs on push event
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  # Job 2: Test (Triggered on push)
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only runs on push event
    needs: build  # Runs after the 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job 3: Deploy (Triggered by workflow_dispatch - manual trigger)
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only runs when manually triggered
    needs: test  # Runs after the 'test' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        run: |
          echo "Deploying project to production..."
          # Add your deployment commands here
