name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  workflow_dispatch:  # Allow manual trigger for the deploy job

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run on push event
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  # Job 2: Test
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run on push event
    needs: build  # Ensure this job runs after 'build' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # Job 3: Deploy (Triggered by workflow_dispatch)
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
    needs: test  # Ensure this job runs after 'test' job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        run: |
          echo "Deploying project to production..."
          # Add your deployment commands here
